site_name: d33kshant
site_url: https://d33kshant.github.io/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.footnote.tooltips
plugins:
  - blog
  - meta
  - social
  - search
# Python markdown extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/d33kshant
      name: d33kshant on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deekshantyadav
      name: d33kshant on LinkedIn
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js