site_name: d33kshant
site_url: https://d33kshant.github.io/
copyright: Copyright &copy; 2025, Deekshant Yadav
# Material theme configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/alpha-d-circle
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.footnote.tooltips
    - toc.follow
# Additional plugins
plugins:
  - blog:
      post_url_format: "{slug}"
      pagination_per_page: 5
  - meta
  - social
  - search
  - tags
# Python markdown extensions
markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.b64
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
# Extra configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/d33kshant
      name: d33kshant on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deekshantyadav
      name: d33kshant on LinkedIn
# Extra JavaScript files
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css