name: build and deploy the blogs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: build html output
        run: |
          make clean
          make html
      - name: upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: _build/html
  
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: blog
          path: blog
      - name: deploy to gh-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: blog

  deploy:
    needs: upload
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4