name: build and deploy the blogs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: install dependencies
        run: |
          pip install -r requirements.txt
      - name: build html output
        run: |
          make clean
          make html
      - name: upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: _build/html
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: deploy to gh-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.build.outputs.artifact_name }}